server:
  port: 8000
  context-path: /simonli
spring:
  application:
    name: simonli
 
  datasource:
    url: jdbc:mysql://localhost:3306/simonli?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8  

logging:
  level:
    root: INFO
    com.sail.simonli: DEBUG