package com.sail.simonli.server.dao;

import com.sail.simonli.server.model.ErrorLog;
import com.sail.simonli.server.model.ErrorLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    int countByExample(ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    int deleteByExample(ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    int insert(ErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    int insertSelective(ErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    List<ErrorLog> selectByExample(ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ErrorLog record, @Param("example") ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ErrorLog record, @Param("example") ErrorLogExample example);
}