package com.sail.simonli.server.model;

import java.io.Serializable;
import java.util.Date;

public class ErrorLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_error_log.occur_date
     *
     * @mbggenerated
     */
    private Date occurDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_error_log.api_name
     *
     * @mbggenerated
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_error_log.error_msg
     *
     * @mbggenerated
     */
    private String errorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_error_log.solution
     *
     * @mbggenerated
     */
    private String solution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_error_log.occur_date
     *
     * @return the value of s_error_log.occur_date
     *
     * @mbggenerated
     */
    public Date getOccurDate() {
        return occurDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_error_log.occur_date
     *
     * @param occurDate the value for s_error_log.occur_date
     *
     * @mbggenerated
     */
    public void setOccurDate(Date occurDate) {
        this.occurDate = occurDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_error_log.api_name
     *
     * @return the value of s_error_log.api_name
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_error_log.api_name
     *
     * @param apiName the value for s_error_log.api_name
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_error_log.error_msg
     *
     * @return the value of s_error_log.error_msg
     *
     * @mbggenerated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_error_log.error_msg
     *
     * @param errorMsg the value for s_error_log.error_msg
     *
     * @mbggenerated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_error_log.solution
     *
     * @return the value of s_error_log.solution
     *
     * @mbggenerated
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_error_log.solution
     *
     * @param solution the value for s_error_log.solution
     *
     * @mbggenerated
     */
    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ErrorLog other = (ErrorLog) that;
        return (this.getOccurDate() == null ? other.getOccurDate() == null : this.getOccurDate().equals(other.getOccurDate()))
            && (this.getApiName() == null ? other.getApiName() == null : this.getApiName().equals(other.getApiName()))
            && (this.getErrorMsg() == null ? other.getErrorMsg() == null : this.getErrorMsg().equals(other.getErrorMsg()))
            && (this.getSolution() == null ? other.getSolution() == null : this.getSolution().equals(other.getSolution()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOccurDate() == null) ? 0 : getOccurDate().hashCode());
        result = prime * result + ((getApiName() == null) ? 0 : getApiName().hashCode());
        result = prime * result + ((getErrorMsg() == null) ? 0 : getErrorMsg().hashCode());
        result = prime * result + ((getSolution() == null) ? 0 : getSolution().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_error_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", occurDate=").append(occurDate);
        sb.append(", apiName=").append(apiName);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", solution=").append(solution);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}